image: trion/ng-cli-karma

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script: 
    - npm install
  artifacts:
    expire_in: 1h
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

tests:
  stage: test
  variables:
    CHROME_BIN: google-chrome
  dependencies:
    - install
  script:
    - npm run test:ci
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'



# deploy:
#     stage: deploy
#     script:
#       - npm install
#       - npm run builddev
#       - npm run deploy
#     environment:
#       name: development
#     only:
#     - master