image: node:latest

cache:
    paths:
        - node_modules/

stages:
    - deploy
  
  
deploy:
    stage: deploy
    script:
      - npm install
      - npm run builddev
      - npm run deploy
    environment:
      name: development
    only:
    - master